resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: slack_github_integration_test_karol                       # <-- replace with your integration
      path: karolh2000/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: art_test_karol                                # <-- replace with your artifactory integration
      sourceRepository: slack-test-local                      # <-- required if registry is Artifactory
      imageName: partnership.jfrog.io/artifactory/slack-test-dev/dbp # partnership.jfrog.io/slack-test-local/dbp     # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_test_karol
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_test_karol
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: slack_test_pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: partnership.jfrog.io/artifactory/slack-test-dev/dbp  # partnership.jfrog.io/slack-test-local/dbp  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: art_test_karol                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: slack-test-local
          integrations:
            - name: art_test_karol                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: slack-test-dev
          integrations:
            - name: art_test_karol
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info

